version: '3'
services:
  meme-bridge:
    container_name: meme-bridge
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:80
    command: ["nginx", "-g", "daemon off;"]
